2020-09-21 18:45:49,176 ERROR: Exception on /follow/Kenedy [GET] [in d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\routes.py", line 121, in follow
    current_user.follow(user)
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\models.py", line 44, in follow
    if not self.is_following(user):
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\models.py", line 53, in is_following
    followers.c.followed_id == user.id).count() > 0
AttributeError: 'BaseQuery' object has no attribute 'id'
2020-09-21 18:50:14,957 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-21 18:50:15,502 ERROR: Exception on /follow/Kenedy [GET] [in d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\routes.py", line 122, in follow
    current_user.follow(user)
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\models.py", line 44, in follow
    if not self.is_following(user):
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\models.py", line 53, in is_following
    followers.c.followed_id == user.id).count() > 0
AttributeError: 'BaseQuery' object has no attribute 'id'
2020-09-22 10:40:53,147 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-22 10:42:02,758 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-22 10:42:31,184 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-22 10:42:53,056 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-22 10:43:18,302 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-22 10:43:25,349 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-22 10:43:59,012 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-22 10:45:06,024 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-22 10:45:28,049 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-22 10:45:28,416 ERROR: Exception on /login [GET] [in d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\routes.py", line 70, in login
    return render_template('login.html', title='Sign In', form=form)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\templates\base.html", line 8, in top-level template code
    <link rel="stylesheet" href="{{ url_for('templates', filename='styles.css') }}">
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'templates' with values ['filename']. Did you mean 'static' instead?
2020-09-22 10:46:37,847 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-22 10:47:20,654 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-22 11:03:20,031 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
