2020-09-21 18:45:49,176 ERROR: Exception on /follow/Kenedy [GET] [in d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\routes.py", line 121, in follow
    current_user.follow(user)
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\models.py", line 44, in follow
    if not self.is_following(user):
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\models.py", line 53, in is_following
    followers.c.followed_id == user.id).count() > 0
AttributeError: 'BaseQuery' object has no attribute 'id'
2020-09-21 18:50:14,957 INFO: Microblog startup [in D:\DEV\Dev\AnyProjects\study_flask_microblog\app\__init__.py:28]
2020-09-21 18:50:15,502 ERROR: Exception on /follow/Kenedy [GET] [in d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\dev\anyprojects\study_flask_microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\routes.py", line 122, in follow
    current_user.follow(user)
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\models.py", line 44, in follow
    if not self.is_following(user):
  File "D:\DEV\Dev\AnyProjects\study_flask_microblog\app\models.py", line 53, in is_following
    followers.c.followed_id == user.id).count() > 0
AttributeError: 'BaseQuery' object has no attribute 'id'
